import { Router, type IRouter } from "express";
import healthRouter from "./health";
import adminRouter from "./admin";
import adminExtraRouter from "./adminExtra";
import bankRouter from "./bank";
import bauCuaGameRouter from "./bauCuaGame";
import bot2HistoryRouter from "./bot2History";
import cardRouter from "./card";
import corebankRouter from "./corebank";
import crashRouter from "./crash";
import duaXeGameRouter from "./duaXeGame";
import gameRouter from "./game";
import hdbankRouter from "./hdbank";
import historyRouter from "./history";
import msbRouter from "./msb";
import msbDigiBankRouter from "./msbDigiBank";
import quayThuGameRouter from "./quayThuGame";
import supportRouter from "./support";
import taiXiuWebRouter from "./taiXiuWeb";
import techcombankRouter from "./techcombank";
import webAuthRouter from "./webAuth";
import webGameRouter from "./webGame";
import webWalletRouter from "./webWallet";
import xocDiaGameRouter from "./xocDiaGame";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/admin", adminRouter);
router.use("/admin", adminExtraRouter);
router.use("/bank", bankRouter);
router.use("/bau-cua", bauCuaGameRouter);
router.use("/bot2-history", bot2HistoryRouter);
router.use("/card", cardRouter);
router.use("/corebank", corebankRouter);
router.use("/crash", crashRouter);
router.use("/dua-xe", duaXeGameRouter);
router.use("/game", gameRouter);
router.use("/hdbank", hdbankRouter);
router.use("/history", historyRouter);
router.use("/msb", msbRouter);
router.use("/msb-digibank", msbDigiBankRouter);
router.use("/quay-thu", quayThuGameRouter);
router.use("/support", supportRouter);
router.use("/tai-xiu", taiXiuWebRouter);
router.use("/techcombank", techcombankRouter);
router.use("/auth", webAuthRouter);
router.use("/web-game", webGameRouter);
router.use("/wallet", webWalletRouter);
router.use("/xoc-dia", xocDiaGameRouter);

export default router;
